
import os
import json

# Configuration
SOURCE_DIR = "js/aura"
OUTPUT_FILE = "js/core/system_data.js"

# Map filenames to System Script IDs (must match ids in js/core/scripts.js)
SCRIPT_MAP = {
    "EROS.js": "sys_eros",
    "INTENT.js": "sys_intent",
    "PULSE.js": "sys_pulse",
    "../core/aura_lib.js": "sys_aura"
}

def main():
    print(f"Building {OUTPUT_FILE} from {SOURCE_DIR}...")
    
    data = {}
    
    if not os.path.exists(SOURCE_DIR):
        print(f"Error: Source directory {SOURCE_DIR} not found.")
        return

    for filename, script_id in SCRIPT_MAP.items():
        filepath = os.path.join(SOURCE_DIR, filename)
        if os.path.exists(filepath):
            print(f"  Reading {filename}...")
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
                data[script_id] = content
        else:
            print(f"  Warning: {filename} not found.")
            data[script_id] = "// Script source not found during build."

    # Generate JS content
    # We use json.dumps to safely escape the string content for JS
    json_content = json.dumps(data, indent=2)
    
    js_output = f"""/*
 * Anansi System Data
 * Generated by build_system_data.py
 * Do not edit manually.
 */

(function(A) {{
    'use strict';
    A.SystemData = {json_content};
    console.log("Anansi: System Data Loaded (" + Object.keys(A.SystemData).length + " scripts).");
}})(window.Anansi);
"""

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js_output)

    print(f"Successfully wrote {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
